version: '3.7'

services:
  db:
    image: postgres:13
    restart: always
    networks:
      - main_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=project
      - PGPORT=5432
    volumes:
      - database-volume:/var/lib/postgresql/data

  main_app:
    build: main-app
    restart: always
    ports:
      - 5050:5050
    networks:
      - main_network
    depends_on:
      - 'db'

networks:
  main_network:

volumes:
  database-volume: